red_diamond: red_diamond_main.c \
	red_diamond_vds.c \
	bitshuffle.c \
	lz4.c \
	bitshuffle_core.c \
	iochain.c
	h5cc -Wall -O2 -o red_diamond red_diamond_main.c \
	red_diamond_vds.c \
	bitshuffle.c \
	lz4.c \
	bitshuffle_core.c \
	iochain.c

